/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 lights.glb --transform 
Files: lights.glb [773.81KB] > /home/weiying-chen/node/react-three-vite/public/lights-transformed.glb [78.59KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model-transformed.glb')
  // Used to control the playback of animations, including playing, pausing, stopping, and adjusting various parameters like loop mode, time scale, and more.
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Water_Control" position={[0, 2.207, 0]} />
        <directionalLight name="Light" intensity={5} decay={2} color="#fdffdf" position={[0.021, 5.778, 12.853]} rotation={[-0.414, 0.004, 1.414]}>
          <group position={[0, 0, -1]} />
        </directionalLight>
        <PerspectiveCamera name="Camera" makeDefault={false} far={100} near={0.1} fov={32.269} position={[20.572, 6.569, 7.486]} rotation={[-0.8, 1.114, 0.746]} />
        <mesh name="Water" geometry={nodes.Water.geometry} material={materials.PaletteMaterial001} />
        <group name="Island">
          <mesh name="Landscape001" geometry={nodes.Landscape001.geometry} material={materials.PaletteMaterial002} />
          <mesh name="Landscape001_1" geometry={nodes.Landscape001_1.geometry} material={materials.PaletteMaterial003} />
          <mesh name="Landscape001_2" geometry={nodes.Landscape001_2.geometry} material={materials.PaletteMaterial004} />
        </group>
        <mesh name="Sun" geometry={nodes.Sun.geometry} material={materials.PaletteMaterial005} position={[0, 1.376, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
